import { Preset } from '@/types';

export const presets: Preset[] = [
  {
    name: 'Dashboard',
    description: 'Layout classique dashboard avec sidebar, header et widgets',
    state: {
      config: {
        columns: 12,
        rows: 8,
        gap: 16,
        gapUnit: 'px',
        padding: 16,
        paddingUnit: 'px',
        containerWidth: 100,
        containerWidthUnit: '%',
        columnWidths: Array(12).fill(1),
        rowHeights: Array(8).fill(1),
      },
      items: [
        {
          id: 'preset-dash-1',
          startCol: 1,
          endCol: 3,
          startRow: 1,
          endRow: 9,
          name: 'Sidebar',
        },
        {
          id: 'preset-dash-2',
          startCol: 3,
          endCol: 13,
          startRow: 1,
          endRow: 2,
          name: 'Header',
        },
        {
          id: 'preset-dash-3',
          startCol: 3,
          endCol: 7,
          startRow: 2,
          endRow: 5,
          name: 'Chart 1',
        },
        {
          id: 'preset-dash-4',
          startCol: 7,
          endCol: 13,
          startRow: 2,
          endRow: 5,
          name: 'Chart 2',
        },
        {
          id: 'preset-dash-5',
          startCol: 3,
          endCol: 9,
          startRow: 5,
          endRow: 9,
          name: 'Table',
        },
        {
          id: 'preset-dash-6',
          startCol: 9,
          endCol: 13,
          startRow: 5,
          endRow: 9,
          name: 'Stats',
        },
      ],
      currentBreakpoint: 'base',
    },
  },
  {
    name: 'Portfolio',
    description: 'Grille de projets type masonry',
    state: {
      config: {
        columns: 12,
        rows: 12,
        gap: 12,
        gapUnit: 'px',
        padding: 24,
        paddingUnit: 'px',
        containerWidth: 1280,
        containerWidthUnit: 'px',
        columnWidths: Array(12).fill(1),
        rowHeights: Array(12).fill(1),
      },
      items: [
        {
          id: 'preset-port-1',
          startCol: 1,
          endCol: 5,
          startRow: 1,
          endRow: 5,
          name: 'Projet 1',
        },
        {
          id: 'preset-port-2',
          startCol: 5,
          endCol: 9,
          startRow: 1,
          endRow: 4,
          name: 'Projet 2',
        },
        {
          id: 'preset-port-3',
          startCol: 9,
          endCol: 13,
          startRow: 1,
          endRow: 6,
          name: 'Projet 3',
        },
        {
          id: 'preset-port-4',
          startCol: 1,
          endCol: 5,
          startRow: 5,
          endRow: 9,
          name: 'Projet 4',
        },
        {
          id: 'preset-port-5',
          startCol: 5,
          endCol: 9,
          startRow: 4,
          endRow: 9,
          name: 'Projet 5',
        },
        {
          id: 'preset-port-6',
          startCol: 9,
          endCol: 13,
          startRow: 6,
          endRow: 10,
          name: 'Projet 6',
        },
        {
          id: 'preset-port-7',
          startCol: 1,
          endCol: 7,
          startRow: 9,
          endRow: 13,
          name: 'Projet 7',
        },
        {
          id: 'preset-port-8',
          startCol: 7,
          endCol: 13,
          startRow: 10,
          endRow: 13,
          name: 'Projet 8',
        },
      ],
      currentBreakpoint: 'base',
    },
  },
  {
    name: 'Landing Page',
    description: 'Hero, features et CTA',
    state: {
      config: {
        columns: 12,
        rows: 10,
        gap: 20,
        gapUnit: 'px',
        padding: 32,
        paddingUnit: 'px',
        containerWidth: 100,
        containerWidthUnit: '%',
        columnWidths: Array(12).fill(1),
        rowHeights: Array(10).fill(1),
      },
      items: [
        {
          id: 'preset-land-1',
          startCol: 1,
          endCol: 13,
          startRow: 1,
          endRow: 5,
          name: 'Hero Section',
        },
        {
          id: 'preset-land-2',
          startCol: 1,
          endCol: 5,
          startRow: 5,
          endRow: 8,
          name: 'Feature 1',
        },
        {
          id: 'preset-land-3',
          startCol: 5,
          endCol: 9,
          startRow: 5,
          endRow: 8,
          name: 'Feature 2',
        },
        {
          id: 'preset-land-4',
          startCol: 9,
          endCol: 13,
          startRow: 5,
          endRow: 8,
          name: 'Feature 3',
        },
        {
          id: 'preset-land-5',
          startCol: 1,
          endCol: 13,
          startRow: 8,
          endRow: 11,
          name: 'CTA Section',
        },
      ],
      currentBreakpoint: 'base',
    },
  },
];

